### ISSUE TITLE
Unexpected output if "closes #bug" appears in PR title

### ISSUE THREAD

**Issue by pdehaan** [ajoslin/conventional-changelog#50]
Not sure if this is exactly the issue, but it was the only consistency I could see between the output in https://github.com/btford/grunt-conventional-changelog/blob/master/CHANGELOG.md and the commits.

Examples:
```
- changelog: cannot generate changelog for first tag () (706a284b, closes `#27`)
- allow 100 characters in commit message () (9982d897, closes `#28`)
```

Note the odd `()` in each of those messages before the commit SHA.

Clicking either of those SHAs in the grunt-conventional-changelog repo's CHANGELOG file gives you these two commits:
- https://github.com/btford/grunt-conventional-changelog/commit/706a284b531719f2bad7a0f9b4bbbd842af47909

  > `fix(changelog): cannot generate changelog for first tag (Closes #27)`

- https://github.com/btford/grunt-conventional-changelog/commit/9982d89753137d474b28d525bf323798dc7210f6

  > `feat(validator): allow 100 characters in commit message (Closes #28)`

**Comment by stevemao** [comment]
No. I don't think so. 

I'm focusing on the next version and most of the code has been rewritten. https://github.com/stevemao/conventional-commits-parser/blob/master/lib/parser.js#L99-L116

Also, I don't think we should allow close in the title but since we need to make it not that strict I don't minding adding this feature.

**Comment by stevemao** [comment]
Please checkout the rewrite on the master branch and see if the problem still exists. Thanks.
