### ISSUE TITLE
npm version command

### ISSUE THREAD

**Issue by markelog** [ajoslin/conventional-changelog#85]
This is the handy command to work with, but it seems `conventional-changelog` can't produce meaningful output if you run `npm version` first.

**Comment by stevemao** [comment]
The problem is you want to keep your changelog changes in the last commit of the release (along with the version change in package.json). If you do `npm version` first your changelog of the current release is in the next release. This is probably not what you want although there are workarounds.

see https://github.com/ajoslin/conventional-changelog#recommended-workflow-when-not-regenerating-the-changelog and the last section of https://github.com/vojtajina/grunt-bump#usage-examples

**Comment by stoffeastrom** [comment]
"scripts": {
    "version": "conventional-changelog -i CHANGELOG.md --overwrite && git add CHANGELOG.md"
}

This way the changelog would be generated with the new version in package.json and commited in the same commit.

However I forgot to set `preset` and now I can't seem to regenerate the CHANGELOG.md

**Comment by stoffeastrom** [comment]
Found it! `-r 0`

**Comment by stevemao** [comment]
I'm using https://gist.github.com/stevemao/280ef22ee861323993a0
