### ISSUE TITLE
migrate from an old version of conventional-changelog

### ISSUE THREAD

**Issue by oupala** [ajoslin/conventional-changelog#95]
I used an old js script with an old version of **conventional-changelog** :

extract from changelog.js :

```js
[...]
changelog({
  version: pkg.version,
  file: destFile,
  commitLink: function (commitHash) {
    var shortCommitHash = commitHash.substring(0, 8);
    var commitUrl = pkg.repository.url + '?p=metalsmith.git&a=commit&h=' + commitHash;
    return '[' + shortCommitHash + '](' + commitUrl + ')';
  }
}, function(err, log) {
  console.log('Here is your changelog!\n\n', log);
  if (err) {
    throw new Error(err);
  }
  fs.writeFileSync(destFile, log);
});
[...]
```

I try to adapt my personal conf to the new version of **conventional-changelog** :

extract from package.json :

`"changelog": "conventional-changelog -p angular -o new-CHANGELOG.md -r 1",`

How can I recover the `commitLink` feature ? I read some documentation from **conventional-changelog** and **conventional-changelog-writer**, but I did not understood the logic behind the refactoring of these modules.

Thanks for any tip.

**Comment by stevemao** [comment]
The current design is completely different from the old. The closest you can get is `context.linkCompare` I think.

**Comment by oupala** [comment]
I'm sorry but I find it very hrad to understand how all this work.

First, could you point me to a doc that explains why and how the curent design differs from the previous one ? (and when ?)

Then, could you explain me how to use `context.linkCompare` and `context.linkReferences` ? Or any working example ?

**Comment by oupala** [comment]
By the way, the context file should be a javascript file, or a json file ?

**Comment by stevemao** [comment]
Because of the breaking changes in this module, the currently design is completely different. If you wanna look at the old docs just dig through old tags. If you are planning using the current one you should probably start from the beginning. In terms of why and when you can just look at the passed issues/commits/convos.

The module was 0.0.x so the api was very unstable. It's still 0.x so there might be breaking changes in the future.

the context file could be either one because basically we just `require` the file. I recently fixed the issue with `require`ing the file but if you have any problem with it, just send a PR with failing test.

**Comment by oupala** [comment]
Right. Thanks for the answer.

**Comment by oupala** [comment]
Your recent fix about requiring the file is fixing the problem for me. I'm waiting for it to be released.
